id: 2a1f1aa2366f49479844fe5da3b088bd
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
  language: bo
  author: ''
  volume: {}
